# For integration tests only
version: "3.6"

services:
  mongo:
    image: mongo:8@sha256:f331890607b5cdce091da9823f91ab1e4c54d31fd572282037880b2eaafff454

  scraper:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/ssu-criminals
