# For integration tests only
version: "3.6"

services:
  mongo:
    image: mongo:8@sha256:e91de87dba7132d55559677c28cffc84aba42b87adffd86349392935878c94cb

  scraper:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/ssu-criminals
