# For integration tests only
version: "3.6"

services:
  mongo:
    image: mongo:8@sha256:1cb283500219e8fc0b61b328ea5a199a395a753d88b17351c58874fb425223cb

  scraper:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/ssu-criminals
