apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ssu-scraper
  namespace: cronjobs
spec:
  schedule: "@weekly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostname: ssu-scraper
          containers:
            - name: ssu-scraper
              image: myrotvorets/ssu-scraper-cronjob
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ssu-scraper-secret
