name: Build Docker Image (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.2.0
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest

      - name: Build images
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            -t myrotvorets/ssu-scraper-cronjob:master \
            .
