name: Build Docker Image (push tag)

on:
  push:
    tags: [ '*' ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.2.0
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest

      - run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Build images
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            -t myrotvorets/ssu-scraper-cronjob:${{ env.RELEASE_VERSION }} \
            .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

      - name: Push images
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            -t myrotvorets/ssu-scraper-cronjob:${{ env.RELEASE_VERSION }} \
            .
