name: Deployment

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      tag:
        default: edge
        required: true
        description: Docker image tag

env:
  IMAGE_NAME: myrotvorets/ssu-scraper-cronjob

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Normalize inputs
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo REFERENCE="${{ github.event.release.tag_name }}" >> "${GITHUB_ENV}"
            echo IMAGE_VER="${{ github.event.release.tag_name }}" >> "${GITHUB_ENV}"
          else
            echo REFERENCE="${{ github.sha }}" >> "${GITHUB_ENV}"
            echo IMAGE_VER="${{ github.event.inputs.tag }}" >> "${GITHUB_ENV}"
          fi

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ env.REFERENCE }}

      - name: Prepare the files
        uses: myrotvorets/composite-actions/prepare-k8s-deployment@master
        with:
          image_version: ${{ env.IMAGE_VER }}
          secret_environment: ${{ secrets.SECRET_ENVIRONMENT }}
          path: iac

      - name: Start deployment
        uses: chrnorm/deployment-action@b11a06a2139d08ec1820b1e13efad139776155a6 # tag=v2.0.2
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: production

      - name: Deploy
        uses: myrotvorets/kubectl-action@49846ef8e3f63df58b7def8a792bbc7407859dd4 # tag=2.0.1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: 1.21
          args: apply -k iac/

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@598d987f3a8dec3817b995f810e6de7c06c92106 # renovate: tag=v1.0.0
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@598d987f3a8dec3817b995f810e6de7c06c92106 # renovate: tag=v1.0.0
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Cleanup
        if: always()
        run: rm -f ./iac/.env
